---
- name: return policies to accept
  ansible.builtin.iptables:
    chain: "{{ item }}"
    policy: ACCEPT
  with_items: [ 'INPUT', 'OUTPUT', 'FORWARD' ]

- name: flush rules
  ansible.builtin.iptables:
    chain: "{{ item }}"
    flush: yes
  with_items: [ 'INPUT', 'OUTPUT', 'FORWARD', 'LOGGING' ]

